apiVersion: v1
kind: Service
metadata:
  name: leantime-service
  labels:
    app: leantime
spec:
  type: LoadBalancer
  selector:
    app: leantime
  ports:
  - port: 80
    targetPort: 8080

